language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
branches:
  only:
  - master
  - production
before_install:
- npm install -g npm@latest
before_deploy:
- npm run build
deploy:
  provider: releases
  api_key:
    secure: cH6N507fabXeIYWrzsvVtq25hKJPYEaMRyoE2bvTDomksANOERg0of2hrNaRKpdcGHlYizk1DOZG/Hmxa2cwHL3xBBWEtzPC9Es/DUqRZJP3AKcaewaEPv1QyuY3k5mY3EQHJWDosyCa2zcp/QVmd63H1x3wZ9lJp/44u+OlGVkI8DVs16sS+irpInvSmdG5SZTgyehQpVzQoP7jhWLmT+gDL9PJkjm37f7ZNoVHpnDa1AEfTP6++Bq1Zo2+vG1+a4gEns/lrqnwy6zhX61CHjMqE03tTuKpKmWhOQnrtIXiTA/9pHFHi/Bcab0yfRj8Z1bqPJJNw3HHo4gIDPpkG+Y7uupXvzHEil1/JI5v633K0GxsbZFwKDILQ/1IadaOjykaNUshZecbSXv67xSUmh2nYq9BtnBr/j1KsmTR6acLs9w9TRFsoskPei3Ox+uBDq8yF13Eqrs0PmAbqEARAoBnrMlUcogRHO2nNTatKLlALuhkf64E6J3BFV3ILXpcffEc+G3zIz4xGAAow72QLQ0x6i2kiOb0kEsPGiQBgwINq28eltT6oGci0BpxO6p+BG3PRUkjEpstyOrIGvyndVClFRh9PB0A9Wbv9BGJclwq964YJzQ8chme+FNJ2OLAHbYDj3wJB6lme+QndFXqPbkkWMadH0DnDARKStkaDTE=
  file: build/jira-quicker-filters.user.js
  on:
    repo: nickcoutsos/jira-quicker-filters-userscript
